<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="5.1 Regresión lineal simple | Ciencia de Datos para Gente Sociable" />
<meta property="og:type" content="book" />



<meta name="github-repo" content="bitsandbricks/datos_sociables" />

<meta name="author" content="Antonio Vazquez Brust" />

<meta name="date" content="2021-08-05" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="text/javascript"></script>

<meta name="description" content="5.1 Regresión lineal simple | Ciencia de Datos para Gente Sociable">

<title>5.1 Regresión lineal simple | Ciencia de Datos para Gente Sociable</title>

<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
/* show arrow before summary tag as in bootstrap
TODO: remove if boostrap in updated in html_document (rmarkdown#1485) */
details > summary {
  display: list-item;
  cursor: pointer;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#section"></a>
<ul>
<li><a href="para-quién-es-esto.html#para-quién-es-esto">¿Para quién es esto?</a></li>
<li><a href="antes-de-empezar.html#antes-de-empezar">Antes de empezar</a></li>
</ul></li>
<li><a href="1-qué-es-la-ciencia-de-datos.html#qué-es-la-ciencia-de-datos"><span class="toc-section-number">1</span> ¿Qué es la ciencia de datos?</a>
<ul>
<li><a href="1-1-qué-significa-hacer-ciencia-de-datos.html#qué-significa-hacer-ciencia-de-datos"><span class="toc-section-number">1.1</span> ¿Qué significa hacer ciencia de datos?</a></li>
</ul></li>
<li><a href="2-una-presentación-a-toda-marcha-de-r.html#una-presentación-a-toda-marcha-de-r"><span class="toc-section-number">2</span> Una presentación a toda marcha de R</a>
<ul>
<li><a href="2-1-nuestro-primer-proyecto-en-r.html#nuestro-primer-proyecto-en-r"><span class="toc-section-number">2.1</span> Nuestro primer proyecto en R</a>
<ul>
<li><a href="2-1-nuestro-primer-proyecto-en-r.html#a-investigar-cual-es-la-diferencia-en-mortalidad-infantil-entre-el-sur-y-el-norte-de-la-ciudad-autónoma-de-buenos-aires"><span class="toc-section-number">2.1.1</span> A investigar: ¿Cual es la diferencia en mortalidad infantil entre el sur y el norte de la Ciudad Autónoma de Buenos Aires?</a></li>
<li><a href="2-1-nuestro-primer-proyecto-en-r.html#crear-un-proyecto-en-rstudio"><span class="toc-section-number">2.1.2</span> Crear un proyecto en RStudio</a></li>
<li><a href="2-1-nuestro-primer-proyecto-en-r.html#escribiendo-un-script"><span class="toc-section-number">2.1.3</span> Escribiendo un script</a></li>
<li><a href="2-1-nuestro-primer-proyecto-en-r.html#cargar-los-datos"><span class="toc-section-number">2.1.4</span> Cargar los datos</a></li>
</ul></li>
<li><a href="2-2-visualización-la-exploración-gráfica-de-la-información.html#visualización-la-exploración-gráfica-de-la-información"><span class="toc-section-number">2.2</span> Visualización: la exploración gráfica de la información</a>
<ul>
<li><a href="2-2-visualización-la-exploración-gráfica-de-la-información.html#haciendo-mapas"><span class="toc-section-number">2.2.1</span> Haciendo mapas</a></li>
<li><a href="2-2-visualización-la-exploración-gráfica-de-la-información.html#agregando-datos"><span class="toc-section-number">2.2.2</span> Agregando datos</a></li>
</ul></li>
<li><a href="2-3-el-veredicto-final.html#el-veredicto-final"><span class="toc-section-number">2.3</span> El veredicto final</a>
<ul>
<li><a href="2-3-el-veredicto-final.html#cuál-es-la-diferencia-en-mortalidad-infantil-entre-el-sur-y-el-norte-de-la-ciudad-autónoma-de-buenos-aires"><span class="toc-section-number">2.3.1</span> ¿Cuál es la diferencia en mortalidad infantil entre el sur y el norte de la Ciudad Autónoma de Buenos Aires?</a></li>
</ul></li>
<li><a href="2-4-ejercicios.html#ejercicios"><span class="toc-section-number">2.4</span> Ejercicios</a></li>
</ul></li>
<li><a href="3-poniendo-los-datos-en-forma.html#poniendo-los-datos-en-forma"><span class="toc-section-number">3</span> Poniendo los datos en forma</a>
<ul>
<li><a href="3-1-primeros-pasos-al-examinar-un-conjunto-de-datos-nuevo.html#primeros-pasos-al-examinar-un-conjunto-de-datos-nuevo"><span class="toc-section-number">3.1</span> Primeros pasos al examinar un conjunto de datos nuevo</a></li>
<li><a href="3-2-cruzando-variables-la-operación-join.html#cruzando-variables-la-operación-join"><span class="toc-section-number">3.2</span> Cruzando variables: la operación <code>join</code></a></li>
<li><a href="3-3-transformando-los-datos.html#transformando-los-datos"><span class="toc-section-number">3.3</span> Transformando los datos</a>
<ul>
<li><a href="3-3-transformando-los-datos.html#seleccionar-columnas-con-select"><span class="toc-section-number">3.3.1</span> Seleccionar columnas con <code>select()</code></a></li>
<li><a href="3-3-transformando-los-datos.html#filtrar-filas-con-filter"><span class="toc-section-number">3.3.2</span> Filtrar filas con <code>filter()</code></a></li>
<li><a href="3-3-transformando-los-datos.html#ordenar-filas-con-arrange"><span class="toc-section-number">3.3.3</span> Ordenar filas con <code>arrange()</code></a></li>
<li><a href="3-3-transformando-los-datos.html#agregar-nuevas-variables-con-mutate"><span class="toc-section-number">3.3.4</span> Agregar nuevas variables con <code>mutate()</code></a></li>
<li><a href="3-3-transformando-los-datos.html#extraer-sumarios-con-summarise"><span class="toc-section-number">3.3.5</span> Extraer sumarios con <code>summarise()</code></a></li>
<li><a href="3-3-transformando-los-datos.html#bonus-el-operador-pipe"><span class="toc-section-number">3.3.6</span> ¡BONUS! El operador “pipe”: <code>%&gt;%</code></a></li>
</ul></li>
<li><a href="3-4-ejercicios-1.html#ejercicios-1"><span class="toc-section-number">3.4</span> Ejercicios</a></li>
</ul></li>
<li><a href="4-visualización.html#visualización"><span class="toc-section-number">4</span> Visualización</a>
<ul>
<li><a href="4-1-una-buena-visualización-para-empezar-el-scatterplot.html#una-buena-visualización-para-empezar-el-scatterplot"><span class="toc-section-number">4.1</span> Una buena visualización para empezar: el <em>scatterplot</em></a></li>
<li><a href="4-2-ajustando-color-y-tamaño.html#ajustando-color-y-tamaño"><span class="toc-section-number">4.2</span> Ajustando color y tamaño</a></li>
<li><a href="4-3-facetado.html#facetado"><span class="toc-section-number">4.3</span> Facetado</a></li>
<li><a href="4-4-gráficos-de-barras.html#gráficos-de-barras"><span class="toc-section-number">4.4</span> Gráficos de barras</a></li>
<li><a href="4-5-histogramas.html#histogramas"><span class="toc-section-number">4.5</span> Histogramas</a></li>
<li><a href="4-6-preparando-una-visualización-para-compartir.html#preparando-una-visualización-para-compartir"><span class="toc-section-number">4.6</span> Preparando una visualización para compartir</a></li>
<li><a href="4-7-otras-visualizaciones.html#otras-visualizaciones"><span class="toc-section-number">4.7</span> Otras visualizaciones</a></li>
<li><a href="4-8-ejercicios-2.html#ejercicios-2"><span class="toc-section-number">4.8</span> Ejercicios</a></li>
</ul></li>
<li><a href="5-modelado-estadístico.html#modelado-estadístico"><span class="toc-section-number">5</span> Modelado estadístico</a>
<ul>
<li><a href="5-1-regresión-lineal-simple.html#regresión-lineal-simple"><span class="toc-section-number">5.1</span> Regresión lineal simple</a>
<ul>
<li><a href="5-1-regresión-lineal-simple.html#regresión-con-una-variable-numérica"><span class="toc-section-number">5.1.1</span> Regresión con una variable numérica</a></li>
<li><a href="5-1-regresión-lineal-simple.html#revolviendo-los-residuos"><span class="toc-section-number">5.1.2</span> Revolviendo los residuos</a></li>
<li><a href="5-1-regresión-lineal-simple.html#regresión-con-una-variable-categórica"><span class="toc-section-number">5.1.3</span> Regresión con una variable categórica</a></li>
</ul></li>
<li><a href="5-2-regresión-con-múltiples-variables.html#regresión-con-múltiples-variables"><span class="toc-section-number">5.2</span> Regresión con múltiples variables</a></li>
<li><a href="5-3-ejercicios-3.html#ejercicios-3"><span class="toc-section-number">5.3</span> Ejercicios</a></li>
</ul></li>
<li><a href="6-información-geográfica-y-mapas.html#información-geográfica-y-mapas"><span class="toc-section-number">6</span> Información geográfica y mapas</a>
<ul>
<li><a href="6-1-los-datos-georreferenciados.html#los-datos-georreferenciados"><span class="toc-section-number">6.1</span> Los datos georreferenciados</a></li>
<li><a href="6-2-formatos-de-archivo.html#formatos-de-archivo"><span class="toc-section-number">6.2</span> Formatos de archivo</a></li>
<li><a href="6-3-explorando-un-archivo-con-información-geográfica.html#explorando-un-archivo-con-información-geográfica"><span class="toc-section-number">6.3</span> Explorando un archivo con información geográfica</a></li>
<li><a href="6-4-visualizando-información-geográfica.html#visualizando-información-geográfica"><span class="toc-section-number">6.4</span> Visualizando información geográfica</a></li>
<li><a href="6-5-volcando-en-el-mapa-información-de-múltiples-fuentes.html#volcando-en-el-mapa-información-de-múltiples-fuentes"><span class="toc-section-number">6.5</span> Volcando en el mapa información de múltiples fuentes</a></li>
<li><a href="6-6-combinando-capas-geográficas.html#combinando-capas-geográficas"><span class="toc-section-number">6.6</span> Combinando capas geográficas</a></li>
<li><a href="6-7-ejercicios-4.html#ejercicios-4"><span class="toc-section-number">6.7</span> Ejercicios</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="regresión-lineal-simple" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Regresión lineal simple</h2>
<p>La encarnación más sencilla de la regresión lineal es la simple o univariada. Tenemos nuestra variable <span class="math inline">\(y\)</span>, numérica, y una sola variable predictora <span class="math inline">\(x\)</span>, que puede ser numérica o categórica.</p>
<p>Para poner en práctica los conceptos repasados en este capítulo, vamos a tomarnos un recreo de los datos de Buenos Aires, haciendo un <em>zoom out</em> hacia las escalas de país, continente y el planeta entero. Contamos con un dataset muy prolijo e interesante recopilado por Gapminder (www.gapminder.org), una organización que busca “hacer comprensible al mundo en base a estadísticas confiables”.</p>
<p>Descarguemos el dataset y echémosle un vistazo como ya sabemos hacer:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="5-1-regresión-lineal-simple.html#cb196-1"></a>data_mundial &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://bitsandbricks.github.io/data/gapminder.csv&quot;</span>)</span>
<span id="cb196-2"><a href="5-1-regresión-lineal-simple.html#cb196-2"></a></span>
<span id="cb196-3"><a href="5-1-regresión-lineal-simple.html#cb196-3"></a><span class="kw">summary</span>(data_mundial)</span></code></pre></div>
<pre><code>##      pais            continente             anio         expVida           pobl                PBI_PC        
##  Length:1704        Length:1704        Min.   :1952   Min.   :23.60   Min.   :     60011   Min.   :   241.2  
##  Class :character   Class :character   1st Qu.:1966   1st Qu.:48.20   1st Qu.:   2793664   1st Qu.:  1202.1  
##  Mode  :character   Mode  :character   Median :1980   Median :60.71   Median :   7023596   Median :  3531.8  
##                                        Mean   :1980   Mean   :59.47   Mean   :  29601212   Mean   :  7215.3  
##                                        3rd Qu.:1993   3rd Qu.:70.85   3rd Qu.:  19585222   3rd Qu.:  9325.5  
##                                        Max.   :2007   Max.   :82.60   Max.   :1318683096   Max.   :113523.1</code></pre>
<p>Con el poder de <code>summary()</code>, podemos decir unas cuantas cosas acerca de nuestros dataset. Las observaciones son de un país, su continente, un año determinado y su expectativa de vida, población y… ¿PBI_PC?. Esa última es PBI per cápita. Que, según parece, hay 12 observaciones por país. Que el rango de años es de 1952 a 2007. Que a lo largo de esos años, la menor expectativa registrada ha sido de 23 años (¡uf!) y la mayor de 82. Que el país menos poblado en el dataset ha tenido apenas más de 60.000 habitantes, mientras que el más populoso ha alcanzado los 1300 millones.</p>
<p>Notemos también que la variable que representa el año de cada medición aparece nombrada como “anio”. Esto se debe a la necesidad de evitar que en el nombre de la variable aparezca la “ñ”, letra que los hispanohablantes apreciamos pero suele traer problemas cuando se cruza con sistemas informáticos.</p>
<div id="regresión-con-una-variable-numérica" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Regresión con una variable numérica</h3>
<p>Hagamos nuestra pregunta: ¿Cómo ha se relaciona el paso del tiempo (variable explicativa) con la expectativa de vida en la Argentina?</p>
<p>Para contestar, primero filtremos los datos que nos interesan:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="5-1-regresión-lineal-simple.html#cb198-1"></a>data_arg &lt;-<span class="st"> </span>data_mundial <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb198-2"><a href="5-1-regresión-lineal-simple.html#cb198-2"></a><span class="st">    </span><span class="kw">filter</span>(pais <span class="op">==</span><span class="st"> &quot;Argentina&quot;</span>)</span>
<span id="cb198-3"><a href="5-1-regresión-lineal-simple.html#cb198-3"></a></span>
<span id="cb198-4"><a href="5-1-regresión-lineal-simple.html#cb198-4"></a>data_arg</span></code></pre></div>
<pre><code>##         pais continente anio expVida     pobl    PBI_PC
## 1  Argentina   Americas 1952  62.485 17876956  5911.315
## 2  Argentina   Americas 1957  64.399 19610538  6856.856
## 3  Argentina   Americas 1962  65.142 21283783  7133.166
## 4  Argentina   Americas 1967  65.634 22934225  8052.953
## 5  Argentina   Americas 1972  67.065 24779799  9443.039
## 6  Argentina   Americas 1977  68.481 26983828 10079.027
## 7  Argentina   Americas 1982  69.942 29341374  8997.897
## 8  Argentina   Americas 1987  70.774 31620918  9139.671
## 9  Argentina   Americas 1992  71.868 33958947  9308.419
## 10 Argentina   Americas 1997  73.275 36203463 10967.282
## 11 Argentina   Americas 2002  74.340 38331121  8797.641
## 12 Argentina   Americas 2007  75.320 40301927 12779.380</code></pre>
<p>Como dijimos en el capítulo de visualización, los scatterplots son útiles para mostrar la relación entre dos variables. Usemos uno para visualizar la relación entre año y expectativa de vida en Argentina, para intentar anticipar los resultados de la regresión lineal.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="5-1-regresión-lineal-simple.html#cb200-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_arg) <span class="op">+</span><span class="st"> </span></span>
<span id="cb200-2"><a href="5-1-regresión-lineal-simple.html#cb200-2"></a><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> expVida)) <span class="op">+</span></span>
<span id="cb200-3"><a href="5-1-regresión-lineal-simple.html#cb200-3"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Correlación entre tiempo y expectativa de vida&quot;</span>,</span>
<span id="cb200-4"><a href="5-1-regresión-lineal-simple.html#cb200-4"></a>         <span class="dt">subtitle =</span> <span class="st">&quot;Argentina&quot;</span>,</span>
<span id="cb200-5"><a href="5-1-regresión-lineal-simple.html#cb200-5"></a>         <span class="dt">y =</span> <span class="st">&quot;expectativa de vida&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
<p>Bien, no necesitamos recurrir a la matemática para saber que tiempo y expectativa de vida están correlacionadas en forma positiva. Esto es, el incremento de una unidad de tiempo en general (o siempre, en este caso) resulta en el incremento de la expectativa de vida. Una correlación <em>negativa</em> sería lo opuesto: que el incremento de la variable explicativa estuviera asociado a un decremento de la variable explicada. Además del <em>signo</em> de una correlación, otra medida importante es su intensidad. La intensidad de una correlación va de -1 (correlación negativa total) a 1 (correlación positiva total). Una correlación de cero significa que las dos variables son por completo independientes. En en ese caso, saber cuánto vale una no nos ayuda a estimar el valor de la otra.</p>
<p>Obtener la correlación entre dos variables es fácil. La función <code>cor()</code> toma dos vectores dos secuencias de valores, y los compara para determinar su grado de correlación. Recurriendo al truco que ya usamos alguna vez, usamos el formato “dataframe$columna” para extraer las columnas de nuestro dataframe que necesitamos:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="5-1-regresión-lineal-simple.html#cb201-1"></a><span class="kw">cor</span>(data_arg<span class="op">$</span>anio, data_arg<span class="op">$</span>expVida)</span></code></pre></div>
<pre><code>## [1] 0.9977816</code></pre>
<p>¿A partir de qué valor consideramos que existe una correlación apreciable? La verdad es que no hay una regla a seguir, pero inventemos una. Si el valor absoluto de la correlación es..</p>
<pre><code>- de 0,7 a 1: de fuerte a total
- de 0,5 a 0,7: de moderada a fuerte
- de 0,3 a 0,7: de débil a moderada
- menor a 0,3: de nula a débil</code></pre>
<p>El valor que obtuvimos se acerca mucho a 1, la correlación casi total. OK, el paso de los años y la expectativa de vida en la Argentina están correlacionados de forma intensa, pero aún desconocemos algo quizás más importante: un valor preciso del “efecto” que el paso de cada año tiene sobre la expectativa de vida. Eso es lo que vamos a determinar con la regresión lineal. Usamos la palabra “efecto” entre comillas para aclarar una de las limitaciones del modelado estadístico: podemos probar correlación, pero no causalidad. Es decir, no podemos probar que una variable causa a la otra; en todo caso, probamos que se mueven juntas y en base a ello podríamos diseñar un experimento que permita comprobar causalidad.</p>
<p>Vamos a la regresión lineal entonces, para medir de una buena vez la correlación entre tiempo y expectativa de vida. Usamos la función <code>lm()</code> (por “linear model”), así:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="5-1-regresión-lineal-simple.html#cb204-1"></a>modelo_exp &lt;-<span class="st"> </span><span class="kw">lm</span>(expVida <span class="op">~</span><span class="st"> </span>anio, <span class="dt">data =</span> data_arg)</span></code></pre></div>
<p>¡Eso es todo! Hemos construido un modelo estadístico; ahora tenemos que aprender a usarlo. Obsérvese que volvió aparecer el simbolillo que denota una fórmula, <code>~</code>. Usado como primer argumento de <code>lm()</code>, significa “<em>expVida</em> vs <em>año</em>”, es decir “estimar el efecto en la variable <em>expVida</em> cuando incrementa el valor de <em>año</em>”, usando los datos contenidos en el dataframe <em>data_arg</em>.</p>
<p>El resultado de <code>lm()</code>, que hemos guardado dentro de la variable <code>modelo_exp</code> es un tipo de objecto con el que no hemos trabajado hasta ahora. No es un dataframe, sino una lista que contiene distintos atributos del modelo estadístico. No hace falta preocuparnos por eso ahora.</p>
<p>Retomando nuestra pregunta… ¿cuál es el efecto? Nos lo dice el modelo cuando lo escribimos.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="5-1-regresión-lineal-simple.html#cb205-1"></a>modelo_exp</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = expVida ~ anio, data = data_arg)
## 
## Coefficients:
## (Intercept)         anio  
##   -389.6063       0.2317</code></pre>
<p>Ahí está. En nuestro modelo, el <em>coeficiente</em> de la variable <em>año</em> (o “anio”, para usar el nombre con el que aparece en los datos) es 0.2317. Significado: incrementando en una unidad la variable año, la variable expectativa de vida se incrementa en 0.2317. Dicho de otra manera, por cada año que pasa la expectativa de vida en la Argentina aumenta casi 3 meses.</p>
<p>El otro coeficiente que aparece, “(Intercept)” es la intersección. En términos de interpretado del modelo, la intersección rara vez tiene utilidad. Para lo que sí sirve es para trazar la línea que permite “predecir” valores para años en los que no tenemos observaciones. Recordemos la fórmula que define una línea recta:</p>
<p><span class="math display">\[ y = a + b \times x \]</span></p>
<p>A cada punto en <span class="math inline">\(x\)</span> le corresponde un valor en <span class="math inline">\(y\)</span> que se obtiene multiplicando a <span class="math inline">\(x\)</span> por la <em>pendiente</em>, <span class="math inline">\(b\)</span>, y sumando la intersección, <span class="math inline">\(a\)</span>. Se le llama “intersección” u “ordenada al origen” porque es el valor donde la recta intersecta con el eje de las <code>y</code>: cuando <span class="math inline">\(x\)</span> vale <span class="math inline">\(0\)</span>, la fórmula nos da <span class="math inline">\(y = b\)</span>.</p>
<p>En una regresión lineal, el “modelo” que creamos es precisamente eso: una línea. Tan simple como eso. Lo que hace a esta linea tan potente, es que la podemos usar bola de cristal: para saber cuanto valdría la variable dependiente ante un valor determinado de la variable predictora, revisamos por donde pasa la línea.</p>
<p>Lo podemos visualizar con ayuda de <code>ggplot()</code>, que por supuesto incluye una función para trazar líneas. Parámetros necesarios: <em>intercept</em> (intersección) y <em>slope</em> (pendiente). Usamos los respectivos valores que nos indica el modelo, <code>-389.6063</code> y <code>o.2317</code>.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="5-1-regresión-lineal-simple.html#cb207-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_arg) <span class="op">+</span><span class="st"> </span></span>
<span id="cb207-2"><a href="5-1-regresión-lineal-simple.html#cb207-2"></a><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> expVida)) <span class="op">+</span></span>
<span id="cb207-3"><a href="5-1-regresión-lineal-simple.html#cb207-3"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Correlación entre tiempo y expectativa de vida&quot;</span>,</span>
<span id="cb207-4"><a href="5-1-regresión-lineal-simple.html#cb207-4"></a>         <span class="dt">subtitle =</span> <span class="st">&quot;Argentina&quot;</span>,</span>
<span id="cb207-5"><a href="5-1-regresión-lineal-simple.html#cb207-5"></a>         <span class="dt">y =</span> <span class="st">&quot;expectativa de vida&quot;</span>,</span>
<span id="cb207-6"><a href="5-1-regresión-lineal-simple.html#cb207-6"></a>         <span class="dt">caption =</span> <span class="st">&quot;con línea de regresión&quot;</span>) <span class="op">+</span></span>
<span id="cb207-7"><a href="5-1-regresión-lineal-simple.html#cb207-7"></a><span class="st">    </span><span class="kw">geom_abline</span>(<span class="kw">aes</span>(<span class="dt">intercept =</span> <span class="fl">-389.6063</span>, <span class="dt">slope =</span> <span class="fl">0.2317</span>), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-118-1.png" width="672" /></p>
<p>Aquí no vemos más que los datos que ya teníamos. Pero proyectemos la línea hacia el futuro. Con <code>xlim()</code> e <code>ylim()</code> podemos definir a mano los límites de nuestro gráfico, haciéndolo ir más allá del rango de los datos que tenemos. La línea sigue siendo la misma, sólo que ahora podemos ver hacia donde va.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="5-1-regresión-lineal-simple.html#cb208-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_arg) <span class="op">+</span><span class="st"> </span></span>
<span id="cb208-2"><a href="5-1-regresión-lineal-simple.html#cb208-2"></a><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> expVida)) <span class="op">+</span></span>
<span id="cb208-3"><a href="5-1-regresión-lineal-simple.html#cb208-3"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Correlación entre tiempo y expectativa de vida&quot;</span>,</span>
<span id="cb208-4"><a href="5-1-regresión-lineal-simple.html#cb208-4"></a>         <span class="dt">subtitle =</span> <span class="st">&quot;Argentina&quot;</span>,</span>
<span id="cb208-5"><a href="5-1-regresión-lineal-simple.html#cb208-5"></a>         <span class="dt">y =</span> <span class="st">&quot;expectativa de vida&quot;</span>,</span>
<span id="cb208-6"><a href="5-1-regresión-lineal-simple.html#cb208-6"></a>         <span class="dt">caption =</span> <span class="st">&quot;con línea de regresión&quot;</span>) <span class="op">+</span></span>
<span id="cb208-7"><a href="5-1-regresión-lineal-simple.html#cb208-7"></a><span class="st">    </span><span class="kw">geom_abline</span>(<span class="kw">aes</span>(<span class="dt">intercept =</span> <span class="fl">-389.6063</span>, <span class="dt">slope =</span> <span class="fl">0.2317</span>), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span></span>
<span id="cb208-8"><a href="5-1-regresión-lineal-simple.html#cb208-8"></a><span class="st">    </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="dv">1950</span>, <span class="dv">2030</span>)) <span class="op">+</span></span>
<span id="cb208-9"><a href="5-1-regresión-lineal-simple.html#cb208-9"></a><span class="st">    </span><span class="kw">ylim</span>(<span class="kw">c</span>(<span class="dv">60</span>, <span class="dv">85</span>))</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>Ahí está la predicción. Según nuestro modelo, para el año 2030 la expectativa de vida en la Argentina habrá superado los 80 años.</p>
<p>Es hora de dar una definición oficial para una regresión lineal, y es esta: es la línea que describe la ecuación:</p>
<p><span class="math display">\[ \hat{y} = b_0 + b_1 \times x \]</span>
Obsérvese que se trata de la ecuación de una recta, <span class="math inline">\(y = a + b \times x\)</span>, con otros nombres. En voz alta, se leería así “Cada predicción del valor de y, llamada <span class="math inline">\(\hat{y}\)</span>, se obtiene multiplicando a la variable predictora <span class="math inline">\(x\)</span> por su coeficiente <span class="math inline">\(b_1\)</span> y sumándole el valor de la intersección <span class="math inline">\(b_0\)</span>”. En otras palabras, a cada valor de <span class="math inline">\(x\)</span> (las observaciones de la variable explicativa) le corresponde un punto en la recta trazada por el modelo. La altura sobre la recta de las <span class="math inline">\(y\)</span> para ese punto es el valor predicho para la variable dependiente.</p>
<p>Ya que estamos, aprendamos otro truco. <code>ggplot()</code> puede agregar a nuestros scatterplots una capa con la línea de la regresión lineal, en forma automática. La función <code>geom_smooth()</code> se usar para explicitar patrones en los datos. Tal como otras de la familia ggplot, espera que se le diga que variables asignar a <code>x</code> e <code>y</code>, más un parámetro <code>method</code> con el método solicitado para trazar una línea de tendencia. Aquí usamos <code>method = "lm"</code> por <em>linear model</em>, el modelo lineal.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="5-1-regresión-lineal-simple.html#cb209-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_arg) <span class="op">+</span><span class="st"> </span></span>
<span id="cb209-2"><a href="5-1-regresión-lineal-simple.html#cb209-2"></a><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> expVida)) <span class="op">+</span></span>
<span id="cb209-3"><a href="5-1-regresión-lineal-simple.html#cb209-3"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Correlación entre tiempo y expectativa de vida&quot;</span>,</span>
<span id="cb209-4"><a href="5-1-regresión-lineal-simple.html#cb209-4"></a>         <span class="dt">subtitle =</span> <span class="st">&quot;Argentina&quot;</span>,</span>
<span id="cb209-5"><a href="5-1-regresión-lineal-simple.html#cb209-5"></a>         <span class="dt">y =</span> <span class="st">&quot;expectativa de vida&quot;</span>,</span>
<span id="cb209-6"><a href="5-1-regresión-lineal-simple.html#cb209-6"></a>         <span class="dt">caption =</span> <span class="st">&quot;con línea de regresión vía geom_smooth()&quot;</span>) <span class="op">+</span></span>
<span id="cb209-7"><a href="5-1-regresión-lineal-simple.html#cb209-7"></a><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> expVida), <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<p>Hacer una regresión lineal se trata de encontrar la línea que atraviesa nuestra nube de puntos de modo tal que la suma de las distancias de cada punto a la línea sea la menor posible. Es un problema matemático que puede resolverse con distintas técnicas (álgebra lineal, geometría, etc) que no vamos a discutir aquí. Confiaremos en R para hacer los cálculos.</p>
<p>En la relación año - expectativa de vida las distancias entre los puntos (las observaciones) y la línea (el modelo) son muy pequeñas. Eso indica que el modelo describe con gran precisión la dinámica de la relación entre las variables analizadas.</p>
<p>En general, es inusual encontrar una correlación tan nítida entre variables “en la vida real”, sobre todo cuando estudiamos procesos complejos cuyo comportamiento describe patrones más complejos que una relación lineal pura. No hace falta ir demasiado lejos para encontrar un ejemplo. Usando el mismo dataset, visualicemos un scatterplot de PBI vs año, agregando la línea de regresión para:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="5-1-regresión-lineal-simple.html#cb211-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_arg) <span class="op">+</span><span class="st"> </span></span>
<span id="cb211-2"><a href="5-1-regresión-lineal-simple.html#cb211-2"></a><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> PBI_PC)) <span class="op">+</span></span>
<span id="cb211-3"><a href="5-1-regresión-lineal-simple.html#cb211-3"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Correlación entre PBI y expectativa de vida&quot;</span>,</span>
<span id="cb211-4"><a href="5-1-regresión-lineal-simple.html#cb211-4"></a>         <span class="dt">subtitle =</span> <span class="st">&quot;Argentina&quot;</span>,</span>
<span id="cb211-5"><a href="5-1-regresión-lineal-simple.html#cb211-5"></a>         <span class="dt">y =</span> <span class="st">&quot;PBI per cápita&quot;</span>) <span class="op">+</span></span>
<span id="cb211-6"><a href="5-1-regresión-lineal-simple.html#cb211-6"></a><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> PBI_PC), <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-121-1.png" width="672" /></p>
<p>Sigue siendo evidente una fuerte tendencia lineal, pero las observaciones ya no se ciñen de forma tan estrecha a la línea idealizada de la regresión.</p>
<p>Obtengamos el modelo del PBI per cápita de la Argentina en relación al paso del tiempo:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="5-1-regresión-lineal-simple.html#cb213-1"></a>modelo_PBI &lt;-<span class="st"> </span><span class="kw">lm</span>(PBI_PC <span class="op">~</span><span class="st"> </span>anio, <span class="dt">data =</span> data_arg)</span>
<span id="cb213-2"><a href="5-1-regresión-lineal-simple.html#cb213-2"></a></span>
<span id="cb213-3"><a href="5-1-regresión-lineal-simple.html#cb213-3"></a>modelo_PBI</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = PBI_PC ~ anio, data = data_arg)
## 
## Coefficients:
## (Intercept)         anio  
##  -162888.14        86.81</code></pre>
<p>Tal como indicaba el <em>scatterplot</em>, obtuvimos un coeficiente positivo. Según el modelo, cada año que pasa resulta en un incremento de 86 dólares en el PBI per cápita del país. Sin embargo, sabemos que no en todos los años se cumple al pie de la letra tal incremento. ¿Debería preocuparnos eso? Una parte importante del análisis basado en regresiones es revisar los desvíos, y decidir si ameritan buscar una explicación. Para ello, lo mejor es empezar por prestar atención a los residuos.</p>
</div>
<div id="revolviendo-los-residuos" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Revolviendo los residuos</h3>
<p>Los residuos, en la jerga estadística, no son otra cosa que las diferencias encontradas entre el valor que predice un modelo para una variable y el valor observado en la práctica. Es decir, el valor para cada punto de <span class="math inline">\(y - \widehat{y}\)</span>. Los residuos representan el desvío de cada observación respecto al valor “esperado” por el modelo.</p>
<p>Cuando los desvíos son pequeños, es decir cuando los residuos son pequeños, decimos que nuestro modelo se ajusta bien a los datos observados. Cuando los residuos son grandes ocurre lo contrario, y quizás deberíamos buscar otra forma de describir, de modelar, la relación entre las variables.</p>
<p>Prestemos atención a los residuos de nuestro modelo de PBV vs. tiempo. Podemos extraer los residuos usando la función <code>residuals()</code>,</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="5-1-regresión-lineal-simple.html#cb215-1"></a>residuos &lt;-<span class="st"> </span><span class="kw">residuals</span>(modelo_PBI)</span>
<span id="cb215-2"><a href="5-1-regresión-lineal-simple.html#cb215-2"></a></span>
<span id="cb215-3"><a href="5-1-regresión-lineal-simple.html#cb215-3"></a>residuos</span></code></pre></div>
<pre><code>##          1          2          3          4          5          6          7          8          9         10 
##  -656.9180  -145.4351  -303.1836   182.5450  1138.5722  1340.5021  -174.6855  -466.9699  -732.2809   492.5240 
##         11         12 
## -2111.1755  1436.5051</code></pre>
<p>agregarlos a nuestro dataframe,</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="5-1-regresión-lineal-simple.html#cb217-1"></a>data_arg &lt;-<span class="st"> </span>data_arg <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">residuo_ml =</span> residuos)</span></code></pre></div>
<p>y visualizarlos comparados con una línea que indica el cero, trazada por <code>geom_hline()</code>. Los residuos cercanos a ese valor son los que corresponden a observaciones a las que el modelo se ajusta bien.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="5-1-regresión-lineal-simple.html#cb218-1"></a><span class="kw">ggplot</span>(data_arg) <span class="op">+</span></span>
<span id="cb218-2"><a href="5-1-regresión-lineal-simple.html#cb218-2"></a><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> residuo_ml)) <span class="op">+</span></span>
<span id="cb218-3"><a href="5-1-regresión-lineal-simple.html#cb218-3"></a><span class="st">    </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span></span>
<span id="cb218-4"><a href="5-1-regresión-lineal-simple.html#cb218-4"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;año&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;residuo del modelo lineal&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-125-1.png" width="672" /></p>
<p>Siempre podemos esperar una cierta divergencia entre las predicciones y los valores observados, por lo que los residuos siempre tendrán (en general) un valor distinto a cero. Lo que quisiéramos ver en un gráfico como este es que los residuos se distribuyan al azar, sin indicios de <em>patrones sistemáticos</em>. Si así fuere, podemos considerar que nuestro modelo es adecuado.</p>
<p>¿Cómo determinamos que no exhiben patrones sistemáticos? Una vez mas, se trata de una evaluación bastante subjetiva, y cada quien estará conforme dependiendo del contexto y la experiencia previa. Aún así podemos argumentar en favor de la adecuación del modelo cuando:</p>
<ol style="list-style-type: decimal">
<li>El promedio de los residuos se aproxima a cero; es decir, que los residuos positivos se cancelan con los negativos, promediando cerca de cero.</li>
<li>El valor de los residuos no depende del valor de <span class="math inline">\(x\)</span>; es decir, no se observa un crecimiento (o decrecimiento) sistemático de la magnitud de los residuos a medida que<span class="math inline">\(x\)</span> crece</li>
</ol>
<p>Por lo visto, nuestro modelo cumple con <code>1.</code> pero no con <code>2</code>, ya que la magnitud de los residuos parece crecer con el paso de los años. Entre todos los puntos, los mayores transgresores son los últimos y corresponden a los años 2002 y 2007. El valor del PBI per cápita observado en 2002 año resultó ser más de 2000 dólares menor al esperado por el modelo, todo un derrumbe. ¿A qué se debe tanta discrepancia? Nuestro modelo no tiene la culpa, es que la realidad tiene sus bemoles. A fines del 2001 la Argentina sufrió la peor crisis financiera de su historia, factor que explica la brusca caída del PBI que revirtió la tendencia al crecimiento de décadas anteriores. Una función que aún no habíamos usado, <code>geom_line()</code>, nos va a permitir trazar una línea que siga el PBI a lo largo de los años, y otra novedad, <code>geom_vline()</code>, se encargará de agregar una línea vertical que señale el año de la crisis:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="5-1-regresión-lineal-simple.html#cb219-1"></a><span class="kw">ggplot</span>(data_arg) <span class="op">+</span><span class="st"> </span></span>
<span id="cb219-2"><a href="5-1-regresión-lineal-simple.html#cb219-2"></a><span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> PBI_PC)) <span class="op">+</span></span>
<span id="cb219-3"><a href="5-1-regresión-lineal-simple.html#cb219-3"></a><span class="st">    </span><span class="kw">geom_vline</span>(<span class="kw">aes</span>(<span class="dt">xintercept =</span> <span class="dv">2001</span>), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></span>
<span id="cb219-4"><a href="5-1-regresión-lineal-simple.html#cb219-4"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Evolución del PBI en la Argentina&quot;</span>,</span>
<span id="cb219-5"><a href="5-1-regresión-lineal-simple.html#cb219-5"></a>         <span class="dt">y =</span> <span class="st">&quot;PBI per cápita&quot;</span>,</span>
<span id="cb219-6"><a href="5-1-regresión-lineal-simple.html#cb219-6"></a>         <span class="dt">caption =</span> <span class="st">&quot;La línea roja indica la ocurrencia de la crisis del 2001&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-126-1.png" width="672" /></p>
<p>Es claro que el modelo se beneficiaría de poder tener en cuenta la irrupción de las crisis en el país. Esto se lograría agregando una variable categórica para cada año, que indique si se trata de un período de crisis. En ese caso, seria un modelo de regresión lineal múltiple (con más de una variable explicativa), incorporando una variable explicativa numérica y otra categórica. Que lástima que nuestro dataset no incluye la variable de las crisis financieras. Si quisiéramos mejorar nuestro modelo con esa información, no nos quedaría mas remedio que salir a buscar los datos. Con suerte, alguien los habrá recopilado por nosotros, y si no, tendríamos que hacerlo por nuestra cuenta. ¡La investigación es un sacerdocio!</p>
<p>En aras de la simplicidad, sigamos practicando con los datos disponibles.</p>
</div>
<div id="regresión-con-una-variable-categórica" class="section level3" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> Regresión con una variable categórica</h3>
<p>El dataset con datos del mundo provisto por Gapminder incluye dos variables categóricas: país y continente. Con 142 países representados, podemos descartar a la primera como variable para realizar un modelo -recordemos que para entender la interrelación de variables, cuantas menos involucremos mejor. Los cinco continentes habitados representan un conjunto mucho más práctico, por lo que la pregunta será “¿Cuánto incide el continente en la expectativa de vida de los países?”</p>
<p>Comencemos por explorar los datos tomando las observaciones más recientes, las de 2007.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="5-1-regresión-lineal-simple.html#cb220-1"></a>data_mundial_<span class="dv">2007</span> &lt;-<span class="st"> </span>data_mundial <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(anio <span class="op">==</span><span class="st"> </span><span class="dv">2007</span>)</span>
<span id="cb220-2"><a href="5-1-regresión-lineal-simple.html#cb220-2"></a></span>
<span id="cb220-3"><a href="5-1-regresión-lineal-simple.html#cb220-3"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_mundial_<span class="dv">2007</span>) <span class="op">+</span></span>
<span id="cb220-4"><a href="5-1-regresión-lineal-simple.html#cb220-4"></a><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> continente, <span class="dt">y =</span> expVida, <span class="dt">color =</span> continente)) <span class="op">+</span></span>
<span id="cb220-5"><a href="5-1-regresión-lineal-simple.html#cb220-5"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Expectativa de vida por continente&quot;</span>,</span>
<span id="cb220-6"><a href="5-1-regresión-lineal-simple.html#cb220-6"></a>         <span class="dt">y =</span> <span class="st">&quot;expectativa de vida&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-127-1.png" width="672" /></p>
<p>Ya podemos vislumbrar que el continente incide en la expectativa de vida, con África sufriendo los números más bajos. La profusión de puntos hace que muchos terminen superpuestos, haciendo imposible determinar cuántos ocupan cada posición (un problema llamado <em>overplotting</em> en inglés). Una variante de <code>geom_point()</code> llamada <code>geom_jitter()</code> resuelve este problema al “sacudir” los puntos, sumando a cada uno un pequeño valor al azar para que se separe de los que comparten su posición. Es un buen ejemplo de la paradoja por la cual reducir la precisión de la información a veces permite entender mejor lo que está ocurriendo. Usamos <code>geom_jitter()</code> igual que <code>geom_point()</code>:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="5-1-regresión-lineal-simple.html#cb221-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_mundial_<span class="dv">2007</span>) <span class="op">+</span></span>
<span id="cb221-2"><a href="5-1-regresión-lineal-simple.html#cb221-2"></a><span class="st">    </span><span class="kw">geom_jitter</span>(<span class="kw">aes</span>(<span class="dt">x =</span> continente, <span class="dt">y =</span> expVida, <span class="dt">color =</span> continente)) <span class="op">+</span></span>
<span id="cb221-3"><a href="5-1-regresión-lineal-simple.html#cb221-3"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Expectativa de vida por continente&quot;</span>,</span>
<span id="cb221-4"><a href="5-1-regresión-lineal-simple.html#cb221-4"></a>         <span class="dt">y =</span> <span class="st">&quot;expectativa de vida&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-128-1.png" width="672" /></p>
<p>Algún ojo avizor habrá notado que la clasificación por color no es necesaria, ya que el continente ya está señalado por su posición en el eje de las <code>x</code>. El color cumple aquí una función más que nada cosmética, en pos de hacer al gráfico maś atractivo a la vista.</p>
<p>También podemos visualizar la diferencia de distribución de expectativa de vida de los países, con un histograma facetado por continente:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="5-1-regresión-lineal-simple.html#cb222-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> data_mundial_<span class="dv">2007</span>) <span class="op">+</span></span>
<span id="cb222-2"><a href="5-1-regresión-lineal-simple.html#cb222-2"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> expVida, <span class="dt">fill =</span> continente)) <span class="op">+</span></span>
<span id="cb222-3"><a href="5-1-regresión-lineal-simple.html#cb222-3"></a><span class="st">    </span><span class="kw">facet_wrap</span>(<span class="op">~</span>continente) <span class="op">+</span></span>
<span id="cb222-4"><a href="5-1-regresión-lineal-simple.html#cb222-4"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Expectativa de vida por continente&quot;</span>,</span>
<span id="cb222-5"><a href="5-1-regresión-lineal-simple.html#cb222-5"></a>         <span class="dt">subtitle =</span> <span class="st">&quot;histogramas&quot;</span>,</span>
<span id="cb222-6"><a href="5-1-regresión-lineal-simple.html#cb222-6"></a>        <span class="dt">x =</span> <span class="st">&quot;expectativa de vida&quot;</span>,</span>
<span id="cb222-7"><a href="5-1-regresión-lineal-simple.html#cb222-7"></a>        <span class="dt">y =</span> <span class="st">&quot;cantidad&quot;</span>)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-129-1.png" width="672" /></p>
<p>Bien, estamos convencidos de que hay una relación entre continente y expectativa de vida, aunque no la hemos cuantificado. Para eso, recurrimos a una regresión lineal con variable explicativa categórica. Se obtiene de la misma manera que antes, no hay cambios en la forma de invocar <code>lm()</code> por el hecho de que la variable ahora sea categórica en vez de numérica.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="5-1-regresión-lineal-simple.html#cb224-1"></a>modelo_exp_continente &lt;-<span class="st"> </span><span class="kw">lm</span>(expVida <span class="op">~</span><span class="st"> </span>continente, <span class="dt">data =</span> data_mundial_<span class="dv">2007</span>)</span>
<span id="cb224-2"><a href="5-1-regresión-lineal-simple.html#cb224-2"></a></span>
<span id="cb224-3"><a href="5-1-regresión-lineal-simple.html#cb224-3"></a></span>
<span id="cb224-4"><a href="5-1-regresión-lineal-simple.html#cb224-4"></a>modelo_exp_continente</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = expVida ~ continente, data = data_mundial_2007)
## 
## Coefficients:
##        (Intercept)  continenteAmericas      continenteAsia    continenteEurope   continenteOceania  
##              54.81               18.80               15.92               22.84               25.91</code></pre>
<p>¿Qué ocurrió aquí? <code>lm()</code> inspeccionó el contenido de la variable “continente” y encontró cinco niveles o categorías. Tomó el primero en orden alfabético, “Africa”, como línea de base. El primer coeficiente de la regresión (la intersección) es el promedio de la expectativa de vida en África. Para cada una de las categorías restantes, el coeficiente representa la diferencia respecto a África de la expectativa de vida promedio en cada uno de los otros continentes. He allí la cuantificación: para un país en las Américas, podemos esperar -en promedio- una expectativa de vida que supera en 18.8 años la de los países africanos. Para un país en Asia, son 15.92 los años adicionales, y así.</p>
<p>Prestemos atención a los residuos. Agregamos al dataframe una columna con el residuo para cada observación,</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="5-1-regresión-lineal-simple.html#cb226-1"></a>data_mundial_<span class="dv">2007</span> &lt;-<span class="st"> </span>data_mundial_<span class="dv">2007</span> <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb226-2"><a href="5-1-regresión-lineal-simple.html#cb226-2"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">residuo_ml =</span> <span class="kw">residuals</span>(modelo_exp_continente))</span></code></pre></div>
<p>y graficamos la dispersión de los residuos en torno a cero, el valor ideal:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="5-1-regresión-lineal-simple.html#cb227-1"></a><span class="kw">ggplot</span>(data_mundial_<span class="dv">2007</span>) <span class="op">+</span></span>
<span id="cb227-2"><a href="5-1-regresión-lineal-simple.html#cb227-2"></a><span class="st">    </span><span class="kw">geom_jitter</span>(<span class="kw">aes</span>(<span class="dt">x =</span> continente, <span class="dt">y =</span> residuo_ml), <span class="dt">width =</span> <span class="fl">0.1</span>) <span class="op">+</span></span>
<span id="cb227-3"><a href="5-1-regresión-lineal-simple.html#cb227-3"></a><span class="st">    </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span></span>
<span id="cb227-4"><a href="5-1-regresión-lineal-simple.html#cb227-4"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;año&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;residuo del modelo lineal&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-132-1.png" width="672" /></p>
<p>Notamos que:</p>
<ol style="list-style-type: decimal">
<li>Los residuos están repartidos en forma pareja entre positivos y negativos. Eso indica que su promedio será cercano a cero, lo cual es bueno.</li>
<li>En Asia hay un país cuyo valor observado está muy por debajo del esperado por el modelo. Se separa tanto de los demás que debemos considerarlo un <em>outlier</em>, un valor tan inusual que amerita ser revisado.</li>
</ol>
<p>Con la magia de los verbos de transformación que sabemos, aislemos a los países en Asia con menor expectativa de vida para identificar al <em>outlier</em>.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="5-1-regresión-lineal-simple.html#cb228-1"></a>data_mundial_<span class="dv">2007</span> <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb228-2"><a href="5-1-regresión-lineal-simple.html#cb228-2"></a><span class="st">    </span><span class="kw">filter</span>(continente <span class="op">==</span><span class="st"> &quot;Asia&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb228-3"><a href="5-1-regresión-lineal-simple.html#cb228-3"></a><span class="st">    </span><span class="kw">arrange</span>(expVida) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb228-4"><a href="5-1-regresión-lineal-simple.html#cb228-4"></a><span class="st">    </span><span class="kw">head</span>()</span></code></pre></div>
<pre><code>##          pais continente anio expVida     pobl    PBI_PC residuo_ml
## 1 Afghanistan       Asia 2007  43.828 31889923  974.5803 -26.900485
## 2        Iraq       Asia 2007  59.545 27499638 4471.0619 -11.183485
## 3    Cambodia       Asia 2007  59.723 14131858 1713.7787 -11.005485
## 4     Myanmar       Asia 2007  62.069 47761980  944.0000  -8.659485
## 5 Yemen, Rep.       Asia 2007  62.698 22211743 2280.7699  -8.030485
## 6       Nepal       Asia 2007  63.785 28901790 1091.3598  -6.943485</code></pre>
<p>Se trata de Afganistán. Como explicación, uno piensa de inmediato en las largas guerras libradas en ese territorio, y en particular la invasión por parte de los Estados Unidos en 2001 -¡otra vez ese año!-. Podemos verificarlo con un gráfico que muestre la evolución de la expectativa de vida según los años.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="5-1-regresión-lineal-simple.html#cb230-1"></a>data_afganistan &lt;-<span class="st"> </span>data_mundial <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(pais <span class="op">==</span><span class="st"> &quot;Afghanistan&quot;</span>)</span>
<span id="cb230-2"><a href="5-1-regresión-lineal-simple.html#cb230-2"></a></span>
<span id="cb230-3"><a href="5-1-regresión-lineal-simple.html#cb230-3"></a><span class="kw">ggplot</span>(data_afganistan) <span class="op">+</span><span class="st"> </span></span>
<span id="cb230-4"><a href="5-1-regresión-lineal-simple.html#cb230-4"></a><span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> anio, <span class="dt">y =</span> expVida)) <span class="op">+</span></span>
<span id="cb230-5"><a href="5-1-regresión-lineal-simple.html#cb230-5"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Expectativa de vida en Afganistán&quot;</span>,</span>
<span id="cb230-6"><a href="5-1-regresión-lineal-simple.html#cb230-6"></a>         <span class="dt">y =</span> <span class="st">&quot;expectativa de vida&quot;</span>)</span></code></pre></div>
<p><img src="ciencia_de_datos_para_gente_sociable_files/figure-html/unnamed-chunk-134-1.png" width="672" /></p>
<p>Vaya sorpresa. A pesar de ser en extremo baja comparada con el resto de Asia, la expectativa de vida en Afganistán en el 2007 es la más alta de la historia, y no sólo eso: ha aumentado con rapidez <em>después</em> del año de la invasión. ¿A qué podemos atribuir entonces la bajísima expectativa de vida? Teniendo en cuenta que el país ha sufrido conflictos bélicos en forma continua desde fines de los ’70, podría tratarse de una tragedia histórica: los años que faltan son los que el país habría alcanzado si las guerras no hubieran alterado su ritmo de progreso.</p>
<p>Dependiendo del esfuerzo que requiera determinar la causa de un <em>outlier</em>, una alternativa razonable es dejarlo de lado. Es un poco cruel, pero realista: cuando tenemos cientos, miles o millones de observaciones, hacer una “poda” de los valores extremos que nuestros modelos no pueden explicar termina siendo la opción más razonable. Dedicar recursos limitados a la caza de una explicación o a complejizar el modelo agregando variables hasta lograr predecir los <em>outliers</em> no tiene sentido cuando se trata de casos aislados y fortuitos. Por otra parte, eliminarlos antes de tiempo podría hacernos ignorar los casos más interesantes de un dataset, los que más información podrían revelar. Existen tratados completos dedicados a la cuestión de como manejar los <em>outliers</em>, pero el conocimiento de dominio es la principal herramienta para decidir que hacer ante casos inusuales… como siempre.</p>
</div>
</div>
<p style="text-align: center;">
<a href="5-modelado-estadístico.html"><button class="btn btn-default">Previous</button></a>
<a href="5-2-regresión-con-múltiples-variables.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
